library(corrplot)
library(tidyverse)

## Predictions ----------------------------------------------------------------
LF1_predict <- predict(lassoFit1, newdata = combined)
LF2_predict <- predict(lassoFit2, newdata = combined)
LF3_predict <- predict(lassoFit3, newdata = combined)
LF4_predict <- predict(lassoFit4, newdata = combined)
LF5_predict <- predict(lassoFit5, newdata = combined)
LF6_predict <- predict(lassoFit6, newdata = combined)
LF7_predict <- predict(lassoFit7, newdata = combined)
LF8_predict <- predict(lassoFit8, newdata = combined)
LF9_predict <- predict(lassoFit9, newdata = combined)
LF10_predict <- predict(lassoFit10, newdata = combined)
LF11_predict <- predict(lassoFit11, newdata = combined)
LF12_predict <- predict(lassoFit12, newdata = combined)
LF13_predict <- predict(lassoFit13, newdata = combined)
LF14_predict <- predict(lassoFit14, newdata = combined)
LF15_predict <- predict(lassoFit15, newdata = combined)
LF16_predict <- predict(lassoFit16, newdata = combined)
LF17_predict <- predict(lassoFit17, newdata = combined)
LF18_predict <- predict(lassoFit18, newdata = combined)
LF19_predict <- predict(lassoFit19, newdata = combined)
LF20_predict <- predict(lassoFit20, newdata = combined)


## Correlation ----------------------------------------------------------------
cor(LF1_predict, combined$voxel1)
cor(LF2_predict, combined$voxel2)
cor(LF3_predict, combined$voxel3)
cor(LF4_predict, combined$voxel4)
cor(LF5_predict, combined$voxel5)
cor(LF6_predict, combined$voxel6)
cor(LF7_predict, combined$voxel7)
cor(LF8_predict, combined$voxel8)
cor(LF9_predict, combined$voxel9)
cor(LF10_predict, combined$voxel10)
cor(LF11_predict, combined$voxel11)
cor(LF12_predict, combined$voxel12)
cor(LF13_predict, combined$voxel13)
cor(LF14_predict, combined$voxel14)
cor(LF15_predict, combined$voxel15)
cor(LF16_predict, combined$voxel16)
cor(LF17_predict, combined$voxel17)
cor(LF18_predict, combined$voxel18)
cor(LF19_predict, combined$voxel19)
cor(LF20_predict, combined$voxel20)