---
title: "Lab 2 - Linguistic Survey Stat 215A, Fall 2017"
author: "Todd Faulkenberry"
date: "9/5/2017"
header-includes:
   - \usepackage{float}
output: 
  pdf_document:
    number_sections: true
---

You don't have to slavishly follow this template. Please use this
structure for your report. Your report should be no more than 12 pages, including figures. Indicate your collaborators on the assignment, if you had
any.


# Introduction


# The Data


## Data quality and cleaning

This dataset isn't as bad as the redwood data, but there are still
some issues. You should discuss them here and describe your strategies
for dealing with them.


## Exploratory Data Analysis

This is where you compare pairs of questions with discussion and plots.


# Dimension reduction methods

This is where you discuss and show plots about the results of whatever
dimension reduction techniques you tried - PCA, hierarchical clustering,
K-means, random projections, etc.


# Stability of findings to perturbation


# Conclusion