---
title: "lab0"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Loading in packages and data


```{r data}
library(tidyverse)
library(readtext)


data("USArrests")
USArrests$State <- attributes(USArrests)$row.names

statecoord <- read.delim('~/Documents/STAT-215A-Fall-2018/week1/lab0/data/stateCoord.txt') %>%
  separate(1, c('State', 'Coord'), sep = " ", extra = "merge") %>%
  separate(Coord, c("drop", "Coord"), sep = '-') %>%
  separate(Coord, c("Long", "Lat"), sep = ' ', extra = "merge") %>%
  select(-drop)

statecoord$Long <- -1 * as.double(statecoord$Long)
statecoord$State <- as.character(attributes(USArrests)$row.names)
```

## Merging datasets

```{r merging}
state_data <- full_join(USArrests, statecoord, by = 'State') %>%
  select(State, UrbanPop, Assault, Murder, Rape, Lat, Long)
```

## Visualizing the data

```{r visualizations}
ggplot(state_data) +
  geom_point(mapping = aes(x = Murder, y = Assault))

ggplot(state_data) +
  geom_point(mapping = aes(x = Rape, y = UrbanPop)) +
  geom_point(x = 44.5, y = 48, color = 'red')

ggplot(state_data) +
  geom_text(mapping = aes(x = Murder, y = Assault, label = State))
```

## Regressions

```{r regressions}
fit <- lm(state_data$UrbanPop ~ state_data$Rape)
  
ggplot(state_data) +
  geom_point(mapping = aes(x = Rape, y = UrbanPop))

plot(fit)
```

I didn't do parts 3-6 of the regression section.